/* caption.js */
/*
		GNU General Public License version 2 or later; see LICENSE.txt
*/
var JCaption=new Class({initialize:function(a){this.selector=a;$$(a).each(function(a){this.createCaption(a)},this)},createCaption:function(a){var f=document.createTextNode(a.title),c=document.createElement("div"),d=document.createElement("p"),e=a.getAttribute("width"),b=a.getAttribute("align");if(!e)e=a.width;b||(b=a.getStyle("float"));if(!b)b=a.style.styleFloat;if(b==""||!b)b="none";d.appendChild(f);d.className=this.selector.replace(".","_");a.parentNode.insertBefore(c,a);c.appendChild(a);a.title!=
""&&c.appendChild(d);c.className=this.selector.replace(".","_");c.className=c.className+" "+b;c.setAttribute("style","float:"+b);c.style.width=e+"px"}});;

/* js_da110b45b06944ce7c4ac43b85d02023.script.js */
var JATypo=new Class({initialize:function(options){this.options=$extend({offsets:{x:10,y:10}},options||{});this.overlay=new Element('div',{'id':'jatypo-overlay'}).inject($(document.body));this.overlay.setStyles({'width':window.getScrollWidth(),'height':window.getScrollHeight()});this.wrapper=$('jatypo-wrap');if(!this.wrapper)return;var button2=new Element('div',{'class':'button2-right jatypo-btn'});if(Browser.ie){button2.innerHTML='<a href="#" onclick="IeCursorFix(); return false;"><span>JATypo</span></a>';}
else
{button2.innerHTML='<span>JATypo</span>';}
this.button=new Element('div',{'class':'button2-left'}).adopt(button2).injectBefore($('editor-xtd-buttons'));this.typos=this.wrapper.getElements('.typo');this.typos.addEvents({'mouseenter':function(){this.addClass('typo-over');var wrapper=$('jatypo-wrap');var sample=this.getElement('.sample');var pos_s=findPos(sample);var pos_w=findPos(wrapper);var scroll_w={x:wrapper.scrollLeft,y:wrapper.scrollTop};var x0=pos_w.x+scroll_w.x;var y0=pos_w.y+scroll_w.y;var w0=wrapper.offsetWidth;var h0=wrapper.offsetHeight;var x1=pos_s.x;var y1=pos_s.y;var w1=sample.offsetWidth;var h1=sample.offsetHeight;if(y1<y0){this.addClass('typo-top').removeClass('typo-bottom')}
if(y1+h1>y0+h0){this.addClass('typo-bottom').removeClass('typo-top')}
if(x1<x0){this.addClass('typo-left').removeClass('typo-right')}
if(x1+w1>x0+w0){this.addClass('typo-right').removeClass('typo-left')}},'mouseleave':function(){this.removeClass('typo-over');},'click':function(){var sample=this.getElement('.sample');var html=sample.innerHTML;if($('jform_content')){jInsertEditorText(html,'jform_content');}
else{jInsertEditorText(html,'jform_articletext');}
$('jatypo-wrap').style.display='none';}});this.wrapper.injectAfter(this.overlay);this.button.addEvent('click',function(event){event=new Event(event);this.position();event.stop();}.bind(this));this.overlay.addEvent('click',function(){this.wrapper.style.display='none';this.overlay.style.display='none';}.bind(this));var doc=null;if($('jform_articletext_ifr')){doc=$('jform_articletext_ifr').contentWindow.document;}
if($('jform_content_ifr')){doc=$('jform_content_ifr').contentWindow.document;}
if(doc){var head=doc.getElementsByTagName('head')[0];var css=doc.createElement('link');css.rel='stylesheet';css.type='text/css';css.href=this.options.typocss;head.appendChild(css);}},locate:function(event){var win={'x':window.getWidth(),'y':window.getHeight()};var scroll={'x':window.getScrollLeft(),'y':window.getScrollTop()};var pwin={'x':this.wrapper.offsetWidth,'y':this.wrapper.offsetHeight};var prop={'x':'left','y':'top'};for(var z in prop){var pos=event.page[z]+this.options.offsets[z];if((pos+pwin[z]-scroll[z])>win[z])pos=event.page[z]-this.options.offsets[z]-pwin[z];this.wrapper.style.prop[z]=pos;};this.wrapper.style.display='block';this.overlay.style.display='block';},position:function(){this.wrapper.style.display='block';this.overlay.style.display='block';var pos=this.button.getPosition();var scroll={'x':window.getScrollLeft(),'y':window.getScrollTop()};var pwin={'x':this.wrapper.offsetWidth,'y':this.wrapper.offsetHeight};this.wrapper.setStyles({'left':pos.x+this.options.offsets.x,'top':pos.y+this.options.offsets.y-pwin.y});}});function findPos(obj){var curleft=curtop=0;if(obj.offsetParent){do{curleft+=obj.offsetLeft;curtop+=obj.offsetTop;}while(obj=obj.offsetParent);}
return{x:curleft,y:curtop};};;

/* js_99240225466f6bbb1945e95241f0801e.core.js */
function switchFontSize(ckname,val){var bd=document.getElementsByTagName('body');if(!bd||!bd.length)return;bd=bd[0];switch(val){case'inc':if(CurrentFontSize+1<7){CurrentFontSize++;}
break;case'dec':if(CurrentFontSize-1>0){CurrentFontSize--;}
break;case'reset':default:CurrentFontSize=DefaultFontSize;}
var newclass='fs'+CurrentFontSize;bd.className=bd.className.replace(new RegExp('fs.?','g'),'');bd.className=trim(bd.className);bd.className+=(bd.className?' ':'')+newclass;createCookie(ckname,CurrentFontSize,365);}
function switchTool(ckname,val){createCookie(ckname,val,365);window.location.reload();}
function cpanel_reset(){var matches=document.cookie.match(new RegExp('(?:^|;)\\s*'+tmpl_name.escapeRegExp()+'_([^=]*)=([^;]*)','g'));if(!matches)return;for(var i=0;i<matches.length;i++){var ck=matches[i].match(new RegExp('(?:^|;)\\s*'+tmpl_name.escapeRegExp()+'_([^=]*)=([^;]*)'));if(ck){createCookie(tmpl_name+'_'+ck[1],'',-1);}}
if(window.location.href.indexOf('?')>-1){window.location.href=window.location.href.substr(0,window.location.href.indexOf('?'));}else{window.location.reload(true);}}
function cpanel_apply(){var elems=document.getElementById('ja-cpanel-main').getElementsByTagName('*');var usersetting={};for(var i=0;i<elems.length;i++){var el=elems[i];if(el.name&&(match=el.name.match(/^user_(.*)$/))){var name=match[1];var value='';if(el.tagName.toLowerCase()=='input'&&(el.type.toLowerCase()=='radio'||el.type.toLowerCase()=='checkbox')){if(el.checked)value=el.value;}else{value=el.value;}
if(usersetting[name]){if(value)usersetting[name]=value+','+usersetting[name];}else{usersetting[name]=value;}}}
for(var k in usersetting){name=tmpl_name+'_'+k;value=usersetting[k].trim();if(value.length>0){createCookie(name,value,365);}}
if(window.location.href.indexOf('?')>-1){window.location.href=window.location.href.substr(0,window.location.href.indexOf('?'));}else{window.location.reload(true);}}
function createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}else{expires="";}
document.cookie=name+"="+value+expires+"; path=/";}
function trim(str,chars){return ltrim(rtrim(str,chars),chars);}
function ltrim(str,chars){chars=chars||"\\s";return str.replace(new RegExp("^["+chars+"]+","g"),"");}
function rtrim(str,chars){chars=chars||"\\s";return str.replace(new RegExp("["+chars+"]+$","g"),"");}
function getScreenWidth(){var x=0;if(self.innerHeight){x=self.innerWidth;}else if(document.documentElement&&document.documentElement.clientHeight){x=document.documentElement.clientWidth;}else if(document.body){x=document.body.clientWidth;}
return x;}
function equalHeight(els){els=$$_(els);if(!els||els.length<2)return;var maxh=0;var els_=[];els.each(function(el,i){if(!el)return;els_[i]=el;var ch=els_[i].getCoordinates().height;maxh=(maxh<ch)?ch:maxh;},this);els_.each(function(el,i){if(!el)return;if(el.getStyle('padding-top')!=null&&el.getStyle('padding-bottom')!=null){if(maxh-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt()>0){el.setStyle('min-height',maxh-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt());}}else{if(maxh>0)el.setStyle('min-height',maxh);}},this);}
function getDeepestWrapper(el){while(el.getChildren().length==1){el=el.getChildren()[0];}
return el;}
function fixHeight(els,group1,group2){els=$$_(els);group1=$$_(group1);group2=$$_(group2);if(!els||!group1)return;var height=0;group1.each(function(el){if(!el)return;height+=el.getCoordinates().height;});if(group2){group2.each(function(el){if(!el)return;height-=el.getCoordinates().height;});}
els.each(function(el,i){if(!el)return;if(el.getStyle('padding-top')!=null&&el.getStyle('padding-bottom')!=null){if(height-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt()>0){el.setStyle('min-height',height-el.getStyle('padding-top').toInt()-el.getStyle('padding-bottom').toInt());}}else{if(height>0){el.setStyle('min-height',height);}}});}
function addFirstLastItem(el){el=$(el);if(!el||!el.getChildren()||!el.getChildren().length)return;el.getChildren()[0].addClass('first-item');el.getChildren()[el.getChildren().length-1].addClass('last-item');}
function $$_(els){if(typeOf(els)=='string')return $$(els);var els_=[];els.each(function(el){el=$(el);if(el)els_.push(el);});return els_;}
$(document).addEvent('domready',function(){$$('[data-dismiss="alert"]').each(function(el){el.addEvent('click',function(){el.getParent().destroy();if($('system-message').getChildren().length==0){Joomla.removeMessages();}});});});;;

/* js_3b0fad8bb089b94056f553374b3cf287.css.js */
window.addEvent('domready',function(){var sfEls=$$('#ja-cssmenu li');sfEls.each(function(li){if((a=li.getElement('a'))&&li.contains(a))li.a=a;else li.a=null;});sfEls.each(function(li){li.addEvent('mouseenter',function(e){clearTimeout(this.timer);if(this.hasClass("havechild"))this.addClass('havechildsfhover').removeClass('havechild');else if(this.hasClass("havesubchild"))this.addClass('havesubchildsfhover').removeClass('havesubchild');this.addClass('sfhover');if(this.a)this.a.addClass('sfhover');});li.addEvent('mouseleave',function(e){this.timer=setTimeout(sfHoverOut.bind(this,e),100);});});});function sfHoverOut(){clearTimeout(this.timer);if(this.hasClass("havechildsfhover"))this.addClass('havechild').removeClass('havechildsfhover');else if(this.hasClass("havesubchildsfhover"))this.addClass('havesubchild').removeClass('havesubchildsfhover');this.removeClass('sfhover');if(this.a)this.a.removeClass('sfhover');};;

/* js_23e90e1b409fd88c3f25fec66fbacbef.script.js */
Element.Events.extend({'wheelup':{type:Element.Events.mousewheel.type,map:function(event){event=new Event(event);if(event.wheel>=0)this.fireEvent('wheelup',event)}},'wheeldown':{type:Element.Events.mousewheel.type,map:function(event){event=new Event(event);if(event.wheel<=0)this.fireEvent('wheeldown',event)}}});var JASlideshowThree=new Class({initialize:function(options){this.options=$extend({buttons:{},interval:5000,handle_event:'click',button_event:'click',box:{},size:240,mode:'horizontal',items:[],handles:[],onWalk:{},handlerBox:null,animation:'fade',animationRepeat:'true',autoPlay:false,languageDirection:null},options||{});this.items=this.options.items;if(this.options.languageDirection=='rtl'){this.modes={horizontal:['right','width'],vertical:['top','height']};}else{this.modes={horizontal:['left','width'],vertical:['top','height']};}
this.box=$(this.options.box);this.buttons={previous:[],next:[],play:[],playback:[],stop:[]};this.allbuttons=[];if(this.options.buttons){for(var action in this.options.buttons){this.addActionButtons(action,$type(this.options.buttons[action])=='array'?this.options.buttons[action]:[this.options.buttons[action]]);}}
this.handles=this.options.handles;if(this.handles){this.addHandleButtons(this.handles);}
if(this.options.handlerBox!=null){this.options.handlerBox.addEvents({'mousewheel':function(e){if(e.wheel<0){e=new Event(e).stop();this.next(true);}
else{e=new Event(e).stop();this.previous(true);}}.bind(this)});}
this.allbuttons.each(function(button){button.addEvent('mouseover',function(){this.addClass('hover');});button.addEvent('mouseout',function(){this.removeClass('hover');});});this.currentIndex=this.options.startItem||0;this.previousIndex=null;this.nextIndex=null;this._auto=null;this.initFx();if(this.options.autoPlay)this.play(this.options.interval,'next',true);this.walk(this.currentIndex);},previous:function(manual){this.lastIndex=this.currentIndex;this.currentIndex+=this.currentIndex>0?-1:this.items.length-1;this.walk(null,manual);},next:function(manual){this.lastIndex=this.currentIndex;this.currentIndex+=this.currentIndex<this.items.length-1?1:1-this.items.length;this.walk(null,manual);},play:function(delay,direction,wait){this.stop();if(!wait){this[direction](false);}
this._auto=this[direction].periodical(delay,this,false);},stop:function(){$clear(this._auto);},walk:function(item,manual){if($defined(item)){this.lastIndex=this.currentIndex;this.currentIndex=parseInt(item);}
this.previousIndex=this.currentIndex+(this.currentIndex>0?-1:this.items.length-1);this.nextIndex=this.currentIndex+(this.currentIndex<this.items.length-1?1:1-this.items.length);if(manual||(this.nextIndex==0&&this.options.animationRepeat=='false')){this.stop();}
if(this.options.onWalk){this.options.onWalk(this.currentIndex,(this.handles?this.handles[this.currentIndex]:null));}
this.animate();if(manual&&this.options.autoPlay){this.play(this.options.interval,'next',true);}},initFx:function(){if(this.options.animation.test(/move/)){this.box.setStyle(this.modes[this.options.mode][1],(this.options.size*this.options.items.length)+'px');this.box.setStyle(this.modes[this.options.mode][0],(-this.currentIndex*this.options.size)+this.options.offset+'px');this.fx=new Fx.Tween(this.box,this.options.fxOptions||{duration:500,wait:false});return;}
this.items.setStyles({'position':'absolute','top':0,'display':'none'});this.items.setStyle(this.modes[this.options.mode][0],0);this.items[this.currentIndex].setStyle('display','block');if(this.options.animation.test(/fade/)){for(var i=0;i<this.items.length;i++){this.items[i].fx=new Fx.Tween(this.items[i],this.options.fxOptions||{duration:500,wait:false});}}},animate:function(){if(this.options.animation.test(/move/)){this.fx.start(this.modes[this.options.mode][0],-this.currentIndex*this.options.size+this.options.offset);return;}
var others=[];for(var i=0;i<this.items.length;i++){this.items[i].fx.pause();if(i!=this.currentIndex&&i!=this.lastIndex)others.push(this.items[i]);}
this.currentIndex=parseInt(this.currentIndex);$$(others).setStyle('display','none');if(this.lastIndex==this.currentIndex){this.items[this.currentIndex].setStyles({'display':'block','opacity':1});}else{this.items[this.currentIndex].setStyles({'display':'block','opacity':0,'z-index':10});this.items[this.lastIndex].setStyles({'z-index':9});}
if(this.options.animation.test(/fade/)){if(this.lastIndex!=this.currentIndex){this.items[this.lastIndex].fx.start('opacity',0);this.items[this.currentIndex].fx.start('opacity',1);}else{this.items[this.currentIndex].fx.start('opacity',1);}
return;}},addHandleButtons:function(handles){for(var i=0;i<handles.length;i++){handles[i].addEvent(this.options.handle_event,this.walk.bind(this,[i,true]));this.allbuttons.push(handles[i]);}},addActionButtons:function(action,buttons){for(var i=0;i<buttons.length;i++){switch(action){case'previous':buttons[i].addEvent(this.options.button_event,this.previous.bind(this,true));break;case'next':buttons[i].addEvent(this.options.button_event,this.next.bind(this,true));break;case'play':buttons[i].addEvent(this.options.button_event,this.play.bind(this,[this.options.interval,'next',false]));break;case'playback':buttons[i].addEvent(this.options.button_event,this.play.bind(this,[this.options.interval,'previous',false]));break;case'stop':buttons[i].addEvent(this.options.button_event,this.stop.bind(this));break;}
this.buttons[action].push(buttons[i]);buttons[i].addEvent(this.options.button_event,function(){this.blur();});this.allbuttons.push(buttons[i]);}}});var JASlideshow2=new Class({initialize:function(element,options){this.options=$extend({startItem:0,showItem:4,mainWidth:360,mainHeight:240,itemWidth:160,itemHeight:160,duration:400,interval:5000,transition:Fx.Transitions.Back.easeOut,thumbOpacity:'0.8',maskDesc:'maskDesc',maskWidth:360,maskHeigth:50,but_prev:'ja-slide-prev',but_next:'ja-slide-next',maskOpacity:'0.8',buttonOpacity:'0.4',overlap:1,navigation:'',animation:'fade',animationRepeat:'true',thumbSpaces:[3,3],autoPlay:false,maskAlignment:'bottom',showbtncontrol:false,urls:'',maskerTransStyle:'opacity',maskerTrans:Fx.Transitions.linear,navePos:'horizontal',languageDirection:null},options||{});if(!this.options.animation.test(/move/))this.options.overlap=0;this.el=$(element);this.fxOptions={duration:this.options.duration,transition:this.options.transition,wait:false}
this.elmain=this.el.getElement('.ja-slide-main-wrap');var conWidth=this.options.overlap?'100%':this.options.mainWidth;this.elmain.setStyles({'width':conWidth,'height':this.options.mainHeight});this.els=this.el.getElements('.ja-slide-item');this.els.setStyles({'width':this.options.mainWidth,'height':this.options.mainHeight});this.options.rearWidth=0;this.options.mainSpace=0;if(this.options.overlap){this.options.mainSpace=10;this.options.rearWidth=Math.ceil((this.elmain.offsetWidth-this.options.mainWidth)/2)-this.options.mainSpace;this.but_prev=this.el.getElement('.'+this.options.but_prev);this.but_next=this.el.getElement('.'+this.options.but_next);this.but_prev.setStyles({'opacity':this.options.buttonOpacity,'width':this.options.rearWidth,'height':this.options.mainHeight});this.but_next.setStyles({'opacity':this.options.buttonOpacity,'width':this.options.rearWidth,'height':this.options.mainHeight});this.but_prev.addEvents({'mouseover':function(){this.but_prev.setStyle('opacity',this.options.buttonOpacity/2);}.bind(this),'mouseout':function(){this.but_prev.setStyle('opacity',this.options.buttonOpacity);}.bind(this)});this.but_next.addEvents({'mouseenter':function(){this.but_next.setStyle('opacity',this.options.buttonOpacity/2);}.bind(this),'mouseleave':function(){this.but_next.setStyle('opacity',this.options.buttonOpacity);}.bind(this)});this.els.setStyle('margin-right',this.options.mainSpace);}
var navWrap=this.el.getElement('.ja-slide-thumbs-wrap');if(this.options.navigation&&navWrap!=null){if(this.options.languageDirection=='rtl'){var modes={horizontal:['right','width','itemWidth'],vertical_left:['top','height','itemHeight'],vertical_right:['top','height','itemHeight']};}else{var modes={horizontal:['left','width','itemWidth'],vertical_left:['top','height','itemHeight'],vertical_right:['top','height','itemHeight']};}
if(this.options.navePos=='vertical_left'||this.options.navePos=='vertical_right'){navWrap.setStyles({'width':this.options.itemWidth,'height':this.options.itemHeight*this.options.showItem});}else{navWrap.setStyles({'width':this.options.itemWidth*this.options.showItem,'height':this.options.itemHeight});}
var thumbs_thumbs=this.el.getElement('.ja-slide-thumbs');thumbs_thumbs.setStyle('left',0);thumbs_thumbs.getChildren().setStyles({'width':this.options.itemWidth,'height':this.options.itemHeight});var thumbs_handles=this.el.getElement('.ja-slide-thumbs-handles');thumbs_handles.setStyle('left',0);thumbs_handles.getChildren().setStyles({'width':this.options.itemWidth,'height':this.options.itemHeight});var thumbsFx_thumbs=new Fx.Tween(thumbs_thumbs,this.fxOptions);var thumbsFx_handles=new Fx.Tween(thumbs_handles,this.fxOptions);this.el.getElement('.ja-slide-thumbs-mask-left').setStyles({'height':this.options.itemHeight,'width':2000,'opacity':this.options.thumbOpacity});this.el.getElement('.ja-slide-thumbs-mask-right').setStyles({'height':this.options.itemHeight,'width':2000,'opacity':this.options.thumbOpacity});this.el.getElement('.ja-slide-thumbs-mask-center').setStyles({'height':this.options.itemHeight,'width':this.options.itemWidth,'opacity':this.options.thumbOpacity});var tmp=this.el.getElement('.ja-slide-thumbs-mask');var thumbs_mask=tmp.setStyles({'width':5000});tmp.setStyle(modes[this.options.navePos][0],this.options.startItem*this.options.itemHeight-2000);var thumbsFx_mask=new Fx.Tween(thumbs_mask,this.fxOptions);}
var navItems=this.el.getElements('.ja-slide-thumb');this.onWalk=function(currentIndex,hander){if(this.options.navigation&&thumbsFx_mask!=null){if(currentIndex<=this.options.startItem||currentIndex-this.options.startItem>=this.options.showItem-1){this.options.startItem=currentIndex-this.options.showItem+2;if(this.options.startItem<0)this.options.startItem=0;if(this.options.startItem>this.els.length-this.options.showItem)this.options.startItem=this.els.length-this.options.showItem;}
var _itemSpace=this.options[modes[this.options.navePos][2]];thumbsFx_mask.start(modes[this.options.navePos][0],(currentIndex-this.options.startItem)*_itemSpace-2000);thumbsFx_thumbs.start(modes[this.options.navePos][0],-this.options.startItem*_itemSpace);thumbsFx_handles.start(modes[this.options.navePos][0],-this.options.startItem*_itemSpace);if($defined(hander)){thumbs_handles.getElements('span').removeClass('active');hander.addClass('active');navItems.removeClass('active');navItems[currentIndex].addClass('active');}}
if(this.options.descMode.test(/load/)&&this.options.showDesc){this.hideDesc();}}
this.maskDesc=this.el.getElement('.'+this.options.maskDesc);this.maskDesc.setStyles({'display':'block','position':'absolute','width':this.options.maskWidth,'height':this.options.maskHeigth});if(this.options.showDesc){if(this.options.animation.test(/move/)&&this.options.overlap){this.options.maskAlignment='left';this.options.maskerTransStyle='opacity';}
this.maskDesc.setStyle(this.options.maskAlignment,this.options.rearWidth+this.options.mainSpace);this.maskDesc.setStyle('opacity',0);if(this.options.maskerTransStyle=='opacity'){this.descFx=new Fx.Tween(this.maskDesc,{duration:400,transition:this.options.maskerTrans});this.descs=this.el.getElements('.ja-slide-desc');this.showDesc=function(){this.descFx.pause();this.descFx.start('opacity',this.options.maskOpacity);};this.hideDesc=function(){this.descFx.pause();this.descFx.start('opacity',0.01);};}else{var sizeOff=this.options.maskAlignment=='top'||this.options.maskAlignment=='bottom'?this.options.maskHeigth:this.options.maskWidth;this.maskDesc.setStyle('opacity',this.options.maskOpacity);this.maskDesc.setStyle(this.options.maskAlignment,-this.options.mainWidth);this.descFx=new Fx.Tween(this.maskDesc,{duration:400,transition:this.options.maskerTrans});this.descs=this.el.getElements('.ja-slide-desc');this.showDesc=function(){this.descFx.pause();this.descFx.start(this.options.maskAlignment,0);};this.hideDesc=function(){this.descFx.pause();this.descFx.start(this.options.maskAlignment,-sizeOff);};}
this.swapDesc=function(currentIndex){if(this.maskDesc.currentIndex==undefined)this.maskDesc.currentIndex=null;if(this.maskDesc.currentIndex==currentIndex)return;if(this.maskDesc.desc!==undefined&&this.maskDesc.desc!=null){this.maskDesc.desc.dispose();this.maskDesc.desc=null;if(!$defined(this.maskDesc.getElement('.inner .readon'))){this.maskDesc.set('html');}}
if(this.descs[currentIndex]&&this.descs[currentIndex].innerHTML)this.maskDesc.desc=this.descs[currentIndex].inject(this.maskDesc);this.maskDesc.currentIndex=currentIndex;}
if(this.options.descMode.test(/mouseover/)){var childs=this.el.getElements('.ja-slide-item');childs.each(function(itm,index){itm.addEvent('mouseover',this.showDesc.bind(this));itm.addEvent('mouseout',this.hideDesc.bind(this));}.bind(this))
this.maskDesc.addEvent('mouseover',this.showDesc.bind(this));this.maskDesc.addEvent('mouseout',this.hideDesc.bind(this));}else{this.maskDesc.setStyle('opacity',this.options.maskOpacity);}}else{this.maskDesc.setStyle('opacity',0);}
this.fxOptions.onComplete=function(){if(this.options.showDesc){this.swapDesc(this.hs.currentIndex);if(this.options.descMode.test(/load/)){this.showDesc();}}}.bind(this);if(this.options.urls){this.el.getElements('.ja-slide-main .ja-slide-item').each(function(item,idx){item.addEvent('click',function(){var url=this.options.urls[idx];if(url){var target=this.options.targets[this.hs.currentIndex];switch(target){case"_blank":{window.open(url,"newWindow");break;}
default:{window.location.href=url;break;}}}}.bind(this));}.bind(this));this.maskDesc.addEvent('click',function(){var url=this.options.urls[this.hs.currentIndex];if(url){var target=this.options.targets[this.hs.currentIndex];switch(target){case"_blank":{window.open(url,"newWindow");break;}
default:{window.location.href=url;break;}}}}.bind(this));}
this.hs=new JASlideshowThree({box:this.el.getElement('.ja-slide-main'),languageDirection:this.options.languageDirection,items:this.els,handlerBox:thumbs_handles,handles:thumbs_handles?thumbs_handles.getChildren():[],fxOptions:this.fxOptions,interval:this.options.interval,onWalk:this.onWalk.bind(this),size:this.options.mainWidth+this.options.mainSpace,animation:this.options.animation,animationRepeat:this.options.animationRepeat,buttons:{previous:this.el.getElements('.ja-slide-prev'),play:this.el.getElements('.ja-slide-play'),stop:this.el.getElements('.ja-slide-stop'),playback:this.el.getElements('.ja-slide-playback'),next:this.el.getElements('.ja-slide-next')},startItem:this.options.startItem,offset:this.options.overlap?this.options.rearWidth-this.options.mainWidth:0,autoPlay:this.options.autoPlay});if(this.options.overlap){var childs=this.hs.box.getChildren();childs[0].clone().inject(this.hs.box);childs[this.hs.items.length-1].clone().injectTop(this.hs.box);this.hs.box.setStyle(this.hs.modes[this.hs.options.mode][1],(this.hs.options.size*(this.hs.items.length+2)+200)+'px');}
this.el.setStyle('visibility','visible');},getFxObjectByMode:function(mode,start,end){switch(mode){case'sideright':return{'left':[start,-end]};break;case'sideleft':return{'left':[start,end]};break;case'sidetop':return{'top':[start,end]};break;case'sidedown':return{'top':[start,-end]};break;case'botleft':return{'top':start,'left':end};break;default:return{'height':[start,end]};break;}},controlMark:function(){}});;;

